### PR TITLE
Allow optional URLs when adding gift to list

### PR DESCRIPTION
**Pull request by mitch-b**
It's fairly common to also include links to specific items. Would you consider adding support for additional data surrounding gift lists?

This is my first time in a meteor application, so any suggestions to clean-up are welcome.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
Awesome suggestion, will help it replace Amazon lists particularly.

**Comment by mitch-b** [comment]
Thanks! I wasn't sure how much you wanted to bring additional libraries into this application, but with the simple validation I added, it'd be more eye-candy for the user to have better alerts like `juliancwirko:s-alert`: 

https://atmospherejs.com/juliancwirko/s-alert
http://s-alert-demo.meteor.com/

**Comment by mitch-b** [comment]
Here's what the visual looks like (for making comments before pulling PR)

Preview Image

**Comment by ocdtrekkie** [comment]
Not my app, just commenting.

**Comment by akumansley** [comment]
Oh, this is great—thanks! Let me take a look at it this evening and we can get it merged in.

**Comment by akumansley** [comment]
Hey @mitch-b, I'm not sure what the right pull-request etiquette is here (my first open source project), so apologies if what I've done is out-of-line—and I'd appreciate any feedback on better PR procedure/mechanics :)

I've tweaked the add UI a bit, and added an in-line UI for errors here: https://github.com/awans/giftr-sandstorm/pull/2

Let me know if you like the change, and I'll merge in both of our commits.

**Comment by mitch-b** [comment]
Hi! sorry, I've been driving across the country. I'm just happy to get this functionality included. Community participation is the only etiquette needed here! thanks for considering this change.

**Pull request merged**
